name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install tools
      run: sudo apt-get install -y sqlite3 gcc

    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: CGO_ENABLED=1 go build -tags "sqlite_foreign_keys" -v ./...

    - name: Test
      run: go test -v ./...
